### PR TITLE
Add Japan 4swordshax support

### PR DESCRIPTION
**Pull request by zoogie**
My minitwlpayload didn't turn out as small as what fincs reported (4564 vs. 5524 for me), but it is still an improvement in size and did actually work with recent-libnds homebrew.

### CODE REVIEW

**Comment by fincs** [comment]
Make sure you are using the latest devkitARM (r47 at the time of writing).

**Comment by zoogie** [comment]
Yeah, devkitpro/arm was freshly installed on my linux machine just to get this compiled.

**Comment by fincs** [comment]
devkitPro is not a program. It is the name of the organization that makes and distributes devkitARM and the rest of the libraries/tools.

Can you post minitwlpayload/build/payload.map somewhere?

**Comment by zoogie** [comment]
Sure, right here.
[payload.zip](https://github.com/yellows8/dsi/files/1295685/payload.zip)

**Comment by fincs** [comment]
Ok, I see what happened. The '4564' figure is the size of the bootloader (minitwlpayload/data/ndsloader.bin), not the entire payload (minitwlpayload/payload.dat). Your mapfile looks correct.

**Pull request merged**
